### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by zeautumn** [imchillin/Anamnesis#976] opened 2022-04-17 18:40 UTC
![Capture d’écran 2022-04-17 144022](https://user-images.githubusercontent.com/94714182/163728018-beda8004-ec5e-43e4-a295-32cf9b55e919.png)

**Comment by Sparrows413** [comment] 2022-04-17 19:00
The tool needs to be updated for 6.1. Have some patience.

**Comment by zeautumn** [comment] 2022-04-17 19:44
> The tool needs to be updated for 6.1. Have some patience.

Ah, perfect. I thought the error was something else. Thank you.

**Comment by Peebs-miqo** [comment] 2022-04-17 23:27
Duplicate of #937

**Closed by Peebs-miqo** 2022-04-17 23:27 UTC
