### ISSUE TITLE
My Anamnesis is being buggy

### ISSUE THREAD

**Issue by Derasdt** [imchillin/Anamnesis#982] opened 2022-04-18 14:03 UTC
Critical Error Anamnesis was unable to recover from this error, and must close
GameDataService Error: Failed to initialize Lumina (are your game files up to date?)

[2022-04-18-10-02-34.txt](https://github.com/imchillin/Anamnesis/files/8506100/2022-04-18-10-02-34.txt)

**Comment by Ani-ki** [comment] 2022-04-18 14:06
Duplicate of #937

**Closed by Ani-ki** 2022-04-18 14:06 UTC

**Comment by Derasdt** [comment] 2022-10-11 07:52
Yea that makes no sense to me

**Comment by EstoyMejor** [comment] 2022-10-11 07:56
Your Anamnesis version is horribly outdated. Or was. 
Update your anamnesis if the issue persists.
