### ISSUE TITLE
Gpose wont freeze characters that are tabbed in Anamnesis

### ISSUE THREAD

**Issue by APauloToren** [imchillin/Anamnesis#1008] opened 2022-04-20 16:31 UTC
When adding actor+ characters (used to change clothing and posing) if they are not in party, but on friendslist.. gpose will not freeze the characters.  Prior to update if they were on my friends list the gpose would allow me to freeze them when i have a tab on the tool opened for that character.  I didnt change anything for this to happen ... am i missing a setting or option?

**Comment by Yuki-Walsh** [comment] 2022-04-21 01:05
looks like a duplicate of #1004. Should be fixed in the next release.

**Closed by Yuki-Walsh** 2022-04-21 01:05 UTC
