### ISSUE TITLE
Lumina Error

### ISSUE THREAD

**Issue by NaofaArach** [imchillin/Anamnesis#962] opened 2022-04-15 17:01 UTC
[2022-04-13-13-51-42.txt](https://github.com/imchillin/Anamnesis/files/8497038/2022-04-13-13-51-42.txt)
[2022-04-14-10-45-17.txt](https://github.com/imchillin/Anamnesis/files/8497039/2022-04-14-10-45-17.txt)
[2022-04-15-12-49-29.txt](https://github.com/imchillin/Anamnesis/files/8497040/2022-04-15-12-49-29.txt)

![image](https://user-images.githubusercontent.com/67977842/163598766-f5ab83de-4864-488c-8915-299ec327458b.png)

I have been trying to get this to work again after the update, I have deleted what i think are all of the files off of my computer and are getting the same error.

**Comment by Ani-ki** [comment] 2022-04-15 17:02
Duplicate of #937

**Closed by Ani-ki** 2022-04-15 17:02 UTC
