### ISSUE TITLE
Actor can't be posed

### ISSUE THREAD

**Issue by Trollsngoblins** [imchillin/Anamnesis#1013] opened 2022-04-21 18:16 UTC
**Describe the bug**
I started by adding an actor (Mannequin). I dressed them up the way I wanted them. Same for my own character. I go into Gpose, disable all motion, but still the actor's posing tab says "Actor motion must be disabled in the Group Pose settings, or actor position must be frozen in animation control".

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Anamnesis.
2. Add actor (Mannequin)
3. Go to 'Customize' tab.
4. Customize both main character and actor.
5. Go into /gpose
6. In /gpose, disable all motion, make sure follow cam in unchecked too.
7. Go to pose tab, enable posing mode for main character. All is fine.
8. Go to actor 2 tab, see error. Can't pose due to the 'Actor motion must be disabled' message.

It seems to ... not want anything not in your party.

**Comment by Yuki-Walsh** [comment] 2022-04-22 03:15
This is caused by #1004, the work around is to unpin the actor before entering gpose, then pin them again once gpose loads.
This is fixed in the next release.

**Closed by Yuki-Walsh** 2022-04-22 03:15 UTC
