### ISSUE TITLE
Character Being Read as NPC in GPOSE

### ISSUE THREAD

**Issue by spookylune** [imchillin/Anamnesis#555] opened 2021-10-02 02:41 UTC
When accessing gpose after initiating Anamnesis, it does not allow me to do things such as lip movements, as well as reading my character as an "NPC (some enemies included)" in the actors.

1. Initiate Anamnesis
2. Go to /gpose in-game
3. Click 'play' for lip-movements
4. Error: "Lip sync cannot be applied to that character"
5. Additionally, actor only disappears when deselecting "NPC (includes some enemies)" instead of "Self"

In the past, I've not had this issue. What should be happening is I initiate Anamnesis, go into gpose, and the character behaves as if they would in normal gpose without Anam running in the background.

[2021-10-01-22-33-08.txt](https://github.com/imchillin/Anamnesis/files/7270777/2021-10-01-22-33-08.txt)
[2021-10-01-22-39-15.txt](https://github.com/imchillin/Anamnesis/files/7270778/2021-10-01-22-39-15.txt)

**Comment by Yuuki-Walsh** [comment] 2021-10-02 03:04
duplicate of #548

**Closed by Yuuki-Walsh** 2021-10-02 03:04 UTC
