### ISSUE TITLE
Character features are modified strangely when entering customize mode.

### ISSUE THREAD

**Issue by Zeemgeem** [imchillin/Anamnesis#1020] opened 2022-04-24 07:58 UTC
**Describe the bug**
Entering the customize mode wipes all my character's default features as selected in the Aesthetician.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Anamnesis
2. Click on the customize character tab
3. Bug occurs. Bug only occurs when the tab is opened for the first time within that instance of Anamnesis.

**Expected behaviour**
My character should look the same before and after pressing the button.

**Log file**
[2022-04-24-03-44-30.txt](https://github.com/imchillin/Anamnesis/files/8549223/2022-04-24-03-44-30.txt)
Below is a short video showing the issue.
https://user-images.githubusercontent.com/83545214/164966238-b95f6a1c-b419-49eb-a7a4-7b32c3b04a3a.mp4

**Comment by AsgardXIV** [comment] 2022-04-24 18:02
Duplicate of #987.

This is a known issue and will be fixed in the next release.

**Closed** 2022-04-25 07:10 UTC
