### ISSUE TITLE
Failed to read game color data 

### ISSUE THREAD

**Issue by Khujacatte** [imchillin/Anamnesis#997] opened 2022-04-19 01:25 UTC
**Describe the bug**
Simply put. When I open Anamnesis, it loads fine except for the color error. 

![anamerror](https://user-images.githubusercontent.com/103974303/163901462-007c110e-4f4e-4768-9170-206eab9ee6d8.JPG)

**To Reproduce**
Steps to reproduce the behaviour:
1. Open program
2. See error

**Expected behaviour**
I expected it to implement file type 922739899
**Log file**
Couldn't find one but there's an included screenshot.

**Comment by Yuki-Walsh** [comment] 2022-04-19 01:27
Duplicate of #986

**Closed by Yuki-Walsh** 2022-04-19 01:27 UTC
