### ISSUE TITLE
Critical Error: No memory scanner

### ISSUE THREAD

**Issue by JagdDrache** [imchillin/Anamnesis#1109] opened 2022-06-06 07:58 UTC
**Describe the bug**
I know there is another person submit the issue but there was no log file. Here is mine.
Unable to use Anamnesis 2022-05-31. Error Shown:

```
AddressService Error: No memory scanner
System.Exception: No memory scanner
   at Anamnesis.Core.Memory.AddressService.GetAddressFromSignature(String name, String signature, Int32 offset, Action`1 callback)
   at Anamnesis.Core.Memory.AddressService.Scan()
   at Anamnesis.Core.Memory.AddressService.Initialize()
   at Anamnesis.Services.ServiceManager.InitializeService(IService service)
   at Anamnesis.Services.ServiceManager.Add[T]()
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Click on Anamnesis'
2. See error

**Expected behaviour**
Should load Anamnesis

**Log file**
[2022-06-06-15-52-37.zip](https://github.com/imchillin/Anamnesis/files/8842759/2022-06-06-15-52-37.zip)

**Comment by RageShoTT** [comment] 2022-06-06 08:25
Did you install the user runtime version of the net 6? or you installed the dev sdk by any chance?
If so, have you tried with the link present in the about page of the github?

**Comment by RageShoTT** [comment] 2022-06-06 08:37
also same issue as #1100

**Comment by JagdDrache** [comment] 2022-06-06 08:49
I was on 6.0.4 and faced the error so i uninstalled and got 6.0.5.

**Comment by RageShoTT** [comment] 2022-06-06 08:52
Have you tried to reset the setting by holding shift after starting anamnesis? (or rename the anamnesis folder in documents)

**Comment by JagdDrache** [comment] 2022-06-06 09:03
Yes i have done the reset setting.

**Comment by RageShoTT** [comment] 2022-06-06 09:07
You have Anamnesis on the desktop by any chances? if so try to move it in a more generic folder like `"C:\Program files"` or `C:\Program files(x86)` 
if this last thing won't help out please take a look at #1100 for update as this is a duplicate of an already open issue, maybe contribute with what we did here there aswell.

**Comment by RageShoTT** [comment] 2022-06-06 09:10
Also add anamnesis to firewall and antivirus exception just to be safe

**Comment by RageShoTT** [comment] 2022-06-06 09:17
thank you very much for your time, i have mentioned this issue on the older one already present as you were active to try some stuff with me, you'll unfortunatly have to wait for now or use the modded client as i'm honestly out of ideas

**Comment by JagdDrache** [comment] 2022-06-06 09:19
All good, thank you for your time. I really appreciate you taking the time to troubleshoot with me. Hope what I have given helps!

**Comment by Yuki-Codes** [comment] 2022-06-06 10:33
ah, this actually looks like #929, but the errors are showing up differently due to the update:
```
[INF] Module Text base: 140696721424384
[INF] Module Text size: 0
[INF] Module Data base: 140696721424384
[INF] Module Data size: 0
```

Going to close this one and continue conversation over in #929.

**Closed by Yuki-Codes** 2022-06-06 10:33 UTC
