### ISSUE TITLE
cant find update to Anamnesis for 6.1

### ISSUE THREAD

**Issue by benjigauthier** [imchillin/Anamnesis#939] opened 2022-04-12 20:20 UTC
Would like to know where an update link is to run Anamnesis on 6.1 seems as it wont run currently

**Comment by blacklion5000** [comment] 2022-04-12 20:34
Hello, the same thing happened to me as to the others with the critical error, I don't know very well how to solve that problem or if there is any update of the program

**Comment by Ani-ki** [comment] 2022-04-12 21:31
Duplicate of #937

**Closed by Ani-ki** 2022-04-12 21:31 UTC
