### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by anatoly-zubov** [imchillin/Anamnesis#949] opened 2022-04-13 19:52 UTC
[2022-04-13-22-47-31.txt](https://github.com/imchillin/Anamnesis/files/8484283/2022-04-13-22-47-31.txt)

**Comment by Naveelea** [comment] 2022-04-13 20:05
The Log says really clear
"2022-04-13 22:47:32.556 +03:00 [FTL] GameDataService Error: Failed to initialize Lumina (Are your game files up to date?)
System.Exception: Failed to initialize Lumina (Are your game files up to date?)"

And if you wouldve took a look at the other issues, you also wouldvve found this one here
https://github.com/imchillin/Anamnesis/issues/937

Patch 6.1 is incompatible with Anamnesis atm. Just wait for the Devs to update the mod. Probably wont happen before or during the easter weekend.

My personal advice, join their Discord (https://discord.gg/KvGJCCnG8t) and stay up to date.

**Comment by Ani-ki** [comment] 2022-04-13 20:12
Duplicate of #937

**Closed by Ani-ki** 2022-04-13 20:12 UTC
Labels: Duplicate
