### ISSUE TITLE
Critical error won't launch after patch 6.1

### ISSUE THREAD

**Issue by jasira1** [imchillin/Anamnesis#955] opened 2022-04-14 14:16 UTC
Won't launch after patch 6.1
Excel data critical error 

2022-04-14 10:12:19.052 -04:00 [WRN] The sheet Anamnesis.GameData.Excel.BattleNpc hash doesn't match the hash generated from the header. Expected: 3717274695 actual: 4253945531
2022-04-14 10:12:19.052 -04:00 [FTL] GameDataService Error: Failed to initialize Lumina (Are your game files up to date?)
System.Exception: Failed to initialize Lumina (Are your game files up to date?)
 ---> Lumina.Excel.Exceptions.ExcelSheetColumnChecksumMismatchException: sheet BNpcBase column hash mismatch! expected hash: dd911c47, actual hash: fd8e0ebb!
   at Anamnesis.GameData.Sheets.ExcelSheet`1.GetSheet(GameData lumina, String name, Language language, Nullable`1 expectedHash)
   at Anamnesis.GameData.Sheets.ExcelSheet`1.GetSheet(GameData lumina)
   at Anamnesis.Services.GameDataService.GetSheet[T]()
   at Anamnesis.Services.GameDataService.Initialize()
   --- End of inner exception stack trace ---
   at Anamnesis.Services.GameDataService.Initialize()
   at Anamnesis.Services.ServiceManager.Add[T]()
2022-04-14 10:13:06.496 -04:00 [INF] 422Mb memory In use.
2022-04-14 10:14:06.510 -04:00 [INF] 422Mb memory In use.

[2022-04-14-10-12-06.txt](https://github.com/imchillin/Anamnesis/files/8489830/2022-04-14-10-12-06.txt)

**Comment by Ani-ki** [comment] 2022-04-14 14:17
Duplicate of #937

**Closed by Ani-ki** 2022-04-14 14:17 UTC
