### ISSUE TITLE
6.1 Anamnesis Crash

### ISSUE THREAD

**Issue by ShiningStarFFXIV** [imchillin/Anamnesis#954] opened 2022-04-14 10:48 UTC
Describe the bug
Anamnesis encounters issues when trying to run it with the game open.

To Reproduce
Steps to reproduce the behaviour:

Log into game
Load Anamnesis
See Lumina error
Anamnesis force closes

Expected behaviour
Anamnesis should work as it did prior to the patch.

Log file
Not sure where to find it sorry.

**Comment by Ani-ki** [comment] 2022-04-14 10:48
Duplicate of #937

**Closed by Ani-ki** 2022-04-14 10:48 UTC
