### ISSUE TITLE
Elezen ears do not properly load with the face.

### ISSUE THREAD

**Issue by shumaimichaelis** [imchillin/Anamnesis#1099] opened 2022-06-03 07:19 UTC
At any point in posing Elezen, rather loading a vanilla expression, loading ONLY a body pose, loading custom poses to fix their ears from other poses, the ears will ffold in different difrections without fail. This happens with every pose, and I know it's not a pose incompatibility (say, loading a miqo pose onto elezen will mess with the face/ears) as I've been posing elezen for quite some time, so I know how to fix them without manually posing them.

**Comment by Yuki-Codes** [comment] 2022-06-06 01:08
duplicate of #1051.
We're still investigating this.

**Closed by Yuki-Codes** 2022-06-06 01:08 UTC
