### ISSUE TITLE
Lumina failed to activate

### ISSUE THREAD

**Issue by kappathefr09** [imchillin/Anamnesis#974] opened 2022-04-17 08:29 UTC
**Describe the bug**
Whenever I attempt to open the app, I am presented with a critical error saying that Lumina was unable to initialize. 

**To Reproduce**
1. Click on Anamnesis.

**Expected behaviour**
The application to run.

**Log file**
[2022-04-17-04-22-02.txt](https://github.com/imchillin/Anamnesis/files/8501222/2022-04-17-04-22-02.txt)

![Screenshot (132)](https://user-images.githubusercontent.com/57207520/163706809-005c8ccd-463f-4ec4-9340-43a778db6a51.png)

**Comment by Peebs-miqo** [comment] 2022-04-17 08:32
Duplicate of #937

**Closed by Peebs-miqo** 2022-04-17 08:32 UTC
