### ISSUE TITLE
Posing/Weather Tools broken when running in Wine under Rosetta

### ISSUE THREAD

**Issue by FleetAdmiralButter** [imchillin/Anamnesis#1171] opened 2022-07-17 05:57 UTC
**Before I go into detail - I do understand that this is in an edge case and I'm not expecting the devs here to support this officially. I'm just hoping that someone more familiar with the inner workings of Anamnesis could point us in the right direction.**

**Describe the bug**
For some context, we're shipping Anamnesis as an officially supported add on in [XIV on Mac](https://github.com/marzent/XIV-on-Mac).

On x86 Intel Macs, Anamnesis works great when running via Wine. However, on Apple M1 machines where Wine is running under Rosetta (which translates x86 instructions into ARM), certain features of Anamnesis are broken. For example, the posing tool and weather controls have no effect. Features that do work, such as customisation of actors, occasionally crash both the game and Anamnesis outright.

This problem seems quite specific to Anamnesis - other tools which rely on manipulating the game process memory, such as Dalamud, have no issues running under Rosetta.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install XIV on Mac and log into your character.
2. Start Anamnesis and try to use the posing/weather tools.

**Expected behaviour**
Posing/weather tools work as on Intel platforms.

**Log file**
Anamnesis logs captured from my M1 (ARM) Mac:
[anam-logs.zip](https://github.com/imchillin/Anamnesis/files/9127093/anam-logs.zip)

Thank you for your help!

**Comment by RageShoTT** [comment] 2022-07-17 06:39
ahhh this will be hard to reproduce as we don't officialy support Mac and we don't have mac system to try it on, maybe @AsgardXIV could help you with this as he was trying to make it work

**Comment by Yuki-Codes** [comment] 2022-07-17 06:45
Hmm. I'd guess the memory manipulation is failing. Anamnesis runs as a superate process from ffxiv, while dalamud injects and runs within the ffxiv process. Logs seem to show random memory failures (invalid module, signatures but found, etc).

It also might be speed related? How fast are the memory operations across so much emulation?

**Comment by FleetAdmiralButter** [comment] 2022-07-17 09:06
> How fast are the memory operations across so much emulation?

I honestly could not quote a hard number here. I can say though that in our performance testing memory speed/latency on ARM hasn't been of concern. The M1/M2 memory controller switches to an x86-compatible mode when executing code via Rosetta so realistically memory performance shouldn't be affected too much.

Are you thinking that a delay in memory operations somewhere might be resulting in Anamnesis trying to operate on a region that no longer contains valid data (i.e, after identifying a valid signature, by the time the write operation goes through that memory address contains something else)?

**Comment by AsgardXIV** [comment] 2022-07-17 10:17
My guess is that it's related to permissions rather than timing given what is broken. I'm assuming M1 has some protection where executable memory can't be written to. I think I may even remember reading about some changes to the memory security model.

Both time control and posing (as well as some of the animation stuff like speed control) patches code and those are the things that are not functioning.

**Comment by AsgardXIV** [comment] 2022-07-17 10:30
Seems likely one of these needs flipping for the wine wrapper or similar. Unfortunately I don't have a lot of time to look at this, but hopefully it's helpful.

https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_disable-executable-page-protection

https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_allow-unsigned-executable-memory

https://developer.apple.com/documentation/apple-silicon/porting-just-in-time-compilers-to-apple-silicon

**Comment by FleetAdmiralButter** [comment] 2022-07-17 13:37
Thanks for the info @AsgardXIV!

XIV on Mac does already ship with most of the app runtime protections disabled to prevent issues with Wine.

Can confirm that Apple Silicon does enforce W^X at a hardware level, so it makes sense that features which rely on modifying game code are broken.

There are macOS APIs to support JIT on AS but since Anamnesis only targets Windows it's likely not possible to use those here.

**Comment by AsgardXIV** [comment] 2022-07-17 19:14
I'm surprised that Dalamud is able to do hooks on M1 given these restrictions.

**Comment by Yuki-Codes** [comment] 2022-08-07 05:29
Going to close this as itz been some time since discussion, and we don't officially support Anamnesis on Mac or Linux here.

**Closed by Yuki-Codes** 2022-08-07 05:29 UTC

**Comment by AsgardXIV** [comment] 2022-08-17 03:16
I've fixed this in #1190
