### ISSUE TITLE
Younger models updated automatically to adults in gpose.

### ISSUE THREAD

**Issue by SmolSleepy** [imchillin/Anamnesis#1072] opened 2022-05-17 06:12 UTC
**Describe the bug**
When loading into gpose with a younger character, they are automatically adjusted to the adult version.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the actor properties tab.
2. Click on npc.
3. Search and select a younger character, e.g. bright-eyed mol girl.
4. Type /gpose in game to load into the posing environment, and the character will become an adult.

**Expected behaviour**
I take parental screenshots for a friend. Birthday parties with his ic daughter, camping, adventuring, etc. In the past this method worked fine, but in the current version 05-04-2022, this bug has come up. If this is not a bug and is intended going forward, I completely understand.

**Log file**
[2022-05-17-01-10-22.txt](https://github.com/imchillin/Anamnesis/files/8705648/2022-05-17-01-10-22.txt)
[2022-05-17-00-24-34.txt](https://github.com/imchillin/Anamnesis/files/8705649/2022-05-17-00-24-34.txt)
[2022-05-17-00-24-11.txt](https://github.com/imchillin/Anamnesis/files/8705650/2022-05-17-00-24-11.txt)

**Comment by Yuki-Codes** [comment] 2022-05-17 07:59
duplicate of #1058.
To get around the limitation, try using a carbuncle or chocobo as the young actor.

**Closed by Yuki-Codes** 2022-05-17 07:59 UTC
