### ISSUE TITLE
Entering equipment tab turns off some facial features

### ISSUE THREAD

**Issue by ArbiterofTruth** [imchillin/Anamnesis#1009] opened 2022-04-20 21:36 UTC
Swapping to the equipment tab when selecting a Hrothgar character turns off some of the facial features such as the beard.

**To Reproduce**
1. Open Anamnesis
2. Select a Hrothgar pc with some facial features turned on
3. Swap to character/equipment tab in Anamnesis

**Expected behaviour**
Anamnesis should be keeping all character customization options, but fails to do so upon the initial switch to the tab. Reapplying those customizations via Anamnesis will keep said features upon switching out of the tab and back.

**Comment by AsgardXIV** [comment] 2022-04-20 21:41
Duplicate of #987. Fixed in the next release.

**Closed** 2022-04-21 06:03 UTC
