### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by Argusx91** [imchillin/Anamnesis#981] opened 2022-04-18 06:54 UTC
Booting up Anamnesis results in a critical error.

1. Boot Anamnesis
2. Receive critical error notification

**Log file**
[2022-04-18-09-48-47.txt](https://github.com/imchillin/Anamnesis/files/8504087/2022-04-18-09-48-47.txt)

Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.
![error](https://user-images.githubusercontent.com/103922609/163768346-16294425-b443-4a67-8777-3a4d046cb8bc.PNG)

**Comment by Peebs-miqo** [comment] 2022-04-18 07:04
Duplicate of #937

**Closed by Peebs-miqo** 2022-04-18 07:04 UTC
