### ISSUE TITLE
Skeleton loading issue (path not found)

### ISSUE THREAD

**Issue by actingcaptain** [imchillin/Anamnesis#609] opened 2021-11-07 01:53 UTC
**Describe the bug**
When I try to change the pose of a minion with me, I get the error 'Cannot bind skeleton to view'. I've tried uninstalling and re-installing, but the issue persist. Character motion is off.

**To Reproduce**
Add minion character to the side tabs.

Go to the skeleton/pose view of the minion. 

The error then appears when you try to generate the skeleton ((it prompts you to generate the skeleton)

**Expected behaviour**

I used to be able to do poses with my minion, but it no longer works.

[2021-11-06-20-37-56.txt](https://github.com/imchillin/Anamnesis/files/7491555/2021-11-06-20-37-56.txt)

**Comment by Ani-ki** [comment] 2021-11-07 02:25
Hi there. Skeletons are currently not working as intended due to changes made under the hood. This has been resolved in the current development build, so I won't close this ticket just yet as I'd like you to try posing the same minion after the update is out and advising if the issue persists for you. Unfortunately in the meantime, we are unable to do anything until that update is out, and thank you for your patience.

**Comment by actingcaptain** [comment] 2021-11-07 02:27
Thanks for your fast response!

**Comment by Ani-ki** [comment] 2021-11-13 23:02
@actingcaptain can you please advise if you're still having issues as of the latest update?

**Comment by Ani-ki** [comment] 2021-11-18 06:35
Closed due to no response from OP.

**Closed by Ani-ki** 2021-11-18 06:35 UTC
Labels: Posing
