### ISSUE TITLE
Mix of app crashing game, not loading items, or actors.

### ISSUE THREAD

**Issue by Bloaky** [imchillin/Anamnesis#599] opened 2021-11-02 01:34 UTC
**Describe the bug**
Sometimes FF14 crashes when I start anamnesis. Sometimes it crashes when I load a saved actor. Sometimes it crashes when I try to add clothing. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open app.
2. May crash/error.
3. If no crash: Click on "Character tab."
4. May crash/error.
5. If no crash: Click on "Load" -> Load character.
6. May crash/error.
7. Try to change clothing.
8. May crash/error.

**Expected behaviour**
Open app. Click character. Load character. Select clothing. Enter Gpose. Begin posing.

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.
[2021-11-02-07-19-28.txt](https://github.com/imchillin/Anamnesis/files/7457140/2021-11-02-07-19-28.txt)
[2021-11-02-07-45-11.txt](https://github.com/imchillin/Anamnesis/files/7457141/2021-11-02-07-45-11.txt)
[2021-11-02-08-03-46.txt](https://github.com/imchillin/Anamnesis/files/7457142/2021-11-02-08-03-46.txt)
[2021-11-02-08-51-27.txt](https://github.com/imchillin/Anamnesis/files/7457143/2021-11-02-08-51-27.txt)
[2021-11-02-08-52-33.txt](https://github.com/imchillin/Anamnesis/files/7457144/2021-11-02-08-52-33.txt)
[2021-11-02-09-03-31.txt](https://github.com/imchillin/Anamnesis/files/7457145/2021-11-02-09-03-31.txt)
[2021-11-02-09-14-37.txt](https://github.com/imchillin/Anamnesis/files/7457146/2021-11-02-09-14-37.txt)
[2021-11-02-09-25-53.txt](https://github.com/imchillin/Anamnesis/files/7457147/2021-11-02-09-25-53.txt)

**Comment by Ani-ki** [comment] 2021-11-03 09:42
We're going to need way more information.
Are you running any other 3rd party tools?
What are you loading the appearances onto?
[**Are you waiting until the game has launched before running the tool?**](https://github.com/imchillin/Anamnesis/wiki/Basic-Setup#installation)

**Comment by Bloaky** [comment] 2021-11-03 23:05
Hi, thanks for the reply.

I run the XIVlauncher.
I'm trying to load a character file. I go to my character load and load a different character's file. Then it crashes. I'm sorry I can't be more descriptive, I'm new to this and the tool, so I have no idea what you're looking for.
I am waiting until the game is fully launched before running the tool.

Hope this helps.

________________________________

**Comment by Ani-ki** [comment] 2021-11-05 10:08
Many of the load actor and crash errors we've seen have since been resolved in the current development build, so I may need to keep this on the backburner until the next version is out and have you try on that. The ticket will stay open, and when the update is out, please try everything you did previously and let us know if the issues persist.

**Comment by Adaiene** [comment] 2021-11-05 18:16
Hi! I'm actually having the same issue. I'm *very* new to all of this so I don't know that I can offer any new insight, but the way the author describes it is exactly what happens to me. Another gpose friend of mine has mentioned the same issue.

**Comment by Ani-ki** [comment] 2021-11-06 01:08
> 
> 
> Hi! I'm actually having the same issue. I'm _very_ new to all of this so I don't know that I can offer any new insight, but the way the author describes it is exactly what happens to me. Another gpose friend of mine has mentioned the same issue.

Just to reiterate on my previous comment (the one before yours), we have more or less resolved these issues in the current development build, so when the new version is out and you've updated it (hopefully in the next couple of days), we'll get you to try doing the same things and keep us posted in case it keeps happening.

**Comment by Ani-ki** [comment] 2021-11-13 23:04
@Bloaky and @Adaiene these issues should have been resolved as of the latest update. Can you please confirm if the issues have been resolved on your end?

**Comment by Sidhenanigans** [comment] 2021-11-14 01:39
I don't know about those two, but the crashes they're describing have gotten exceptionally worse after updating this morning.  It's basically unusable, since the game crashes almost every time after loading a character or entering gpose now.  I'm attaching all my log files from today, in case that helps.
[2021-11-13-07-18-55.txt](https://github.com/imchillin/Anamnesis/files/7533021/2021-11-13-07-18-55.txt)
[2021-11-13-07-20-02.txt](https://github.com/imchillin/Anamnesis/files/7533022/2021-11-13-07-20-02.txt)
[2021-11-13-07-22-08.txt](https://github.com/imchillin/Anamnesis/files/7533023/2021-11-13-07-22-08.txt)
[2021-11-13-07-24-30.txt](https://github.com/imchillin/Anamnesis/files/7533024/2021-11-13-07-24-30.txt)
[2021-11-13-07-31-26.txt](https://github.com/imchillin/Anamnesis/files/7533025/2021-11-13-07-31-26.txt)
[2021-11-13-17-08-24.txt](https://github.com/imchillin/Anamnesis/files/7533026/2021-11-13-17-08-24.txt)
[2021-11-13-18-22-30.txt](https://github.com/imchillin/Anamnesis/files/7533027/2021-11-13-18-22-30.txt)
[2021-11-13-18-27-22.txt](https://github.com/imchillin/Anamnesis/files/7533028/2021-11-13-18-27-22.txt)
[2021-11-13-18-33-57.txt](https://github.com/imchillin/Anamnesis/files/7533029/2021-11-13-18-33-57.txt)

**Comment by Ani-ki** [comment] 2021-11-14 01:42
> 
> 
> I don't know about those two, but the crashes they're describing have gotten exceptionally worse after updating this morning. It's basically unusable, since the game crashes almost every time after loading a character or entering gpose now. I'm attaching all my log files from today, in case that helps. [2021-11-13-07-18-55.txt](https://github.com/imchillin/Anamnesis/files/7533021/2021-11-13-07-18-55.txt) [2021-11-13-07-20-02.txt](https://github.com/imchillin/Anamnesis/files/7533022/2021-11-13-07-20-02.txt) [2021-11-13-07-22-08.txt](https://github.com/imchillin/Anamnesis/files/7533023/2021-11-13-07-22-08.txt) [2021-11-13-07-24-30.txt](https://github.com/imchillin/Anamnesis/files/7533024/2021-11-13-07-24-30.txt) [2021-11-13-07-31-26.txt](https://github.com/imchillin/Anamnesis/files/7533025/2021-11-13-07-31-26.txt) [2021-11-13-17-08-24.txt](https://github.com/imchillin/Anamnesis/files/7533026/2021-11-13-17-08-24.txt) [2021-11-13-18-22-30.txt](https://github.com/imchillin/Anamnesis/files/7533027/2021-11-13-18-22-30.txt) [2021-11-13-18-27-22.txt](https://github.com/imchillin/Anamnesis/files/7533028/2021-11-13-18-27-22.txt) [2021-11-13-18-33-57.txt](https://github.com/imchillin/Anamnesis/files/7533029/2021-11-13-18-33-57.txt)

Just so we can rule it out, can you please make sure you're on the [latest version of the .NET Desktop Runtime](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.12-windows-x64-installer)? Your log says you're on 5.0.7.

**Comment by Adaiene** [comment] 2021-11-14 01:49
I went be able to check for a few days, but I'll report back ASAP.

**Comment by Sidhenanigans** [comment] 2021-11-14 01:51
Just updated to 5.0.12 right now and tried Anamnesis again; it crashed after loading two characters
[2021-11-13-18-50-15.txt](https://github.com/imchillin/Anamnesis/files/7533048/2021-11-13-18-50-15.txt)
.

**Comment by Ani-ki** [comment] 2021-11-29 22:21
@Bloaky @Adaiene @Sidhenanigans can you please advise if you're still having these issues as of the latest update?

**Comment by Adaiene** [comment] 2021-11-29 22:35
So far I haven't had any crash issues. It's working great!

**Comment by Sidhenanigans** [comment] 2021-11-29 23:48
After the latest update, it's all good for me. No more crashes!

**Comment by Ani-ki** [comment] 2021-11-29 23:57
I've not heard from the OP in almost a month, but since you have both confirmed there are no issues on your end, I'll consider this closed, and OP can contact us if they're still having issues. Thank you for getting back to me!

**Closed by Ani-ki** 2021-11-29 23:57 UTC
Labels: Bug, Appearance, Actor, FFXIV Crash, Lumina, More info required
