### ISSUE TITLE
Process Module Invalid error

### ISSUE THREAD

**Issue by Tequilaselai** [imchillin/Anamnesis#1042] opened 2022-05-02 00:27 UTC
**Describe the bug**
Anamnesis does not initialize at all with error message "Critical Error: The tool was unable to recover from this error, and must close."

**To Reproduce**
Steps to reproduce the behaviour:
1. Log in to FFXIV
2. Log in to character
3. Begin Gpose
4. Run Anamnesis as admin
5. See error
![image](https://user-images.githubusercontent.com/70240340/166170731-99ce5c5c-ea0a-49f0-a831-942c30e22244.png)

**Expected behaviour**
Anamnesis to run as normal

**Log files**
[2022-05-01-20-17-05.txt](https://github.com/imchillin/Anamnesis/files/8600012/2022-05-01-20-17-05.txt)
[2022-05-01-20-24-58.txt](https://github.com/imchillin/Anamnesis/files/8600025/2022-05-01-20-24-58.txt)
[2022-05-01-20-26-33.txt](https://github.com/imchillin/Anamnesis/files/8600028/2022-05-01-20-26-33.txt)
each file is an instance of attempting to open.

**Additional Notes**

1. Currently have .NET Desktop Runtime 5.0.16 installed, and reinstalled multiple times
2. Uninstalled Avast antivirus and currently using Windows Defender.
3. Whitelisted both the designated folder containing all Anamnesis files and the .exe file specifically.
4. TexTools is installed.

**Comment by Yuki-Walsh** [comment] 2022-05-02 06:16
this is a duplicate of #929, so going to keep conversation there.

**Closed by Yuki-Walsh** 2022-05-02 06:16 UTC
