### ISSUE TITLE
Critical error even if everything is up to date

### ISSUE THREAD

**Issue by lealin92** [imchillin/Anamnesis#970] opened 2022-04-17 01:16 UTC
**Describe the bug**
Ana showing up error that lumia is not running and ask if files are up to date ( i downloaed the newest version of Ana and Net is fixed and up to date)

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Ana
2. First window thats Ana is not up to date to patch (even if is the newest Ana version)
3. Second window of critical error
4. close Ana

**Expected behaviour**
1. Open Ana
2. Ana window is showing ready to work

**Log file**
[2022-04-17-03-04-06.txt](https://github.com/imchillin/Anamnesis/files/8500839/2022-04-17-03-04-06.txt)

**Comment by Ani-ki** [comment] 2022-04-17 01:26
Duplicate of #937

**Closed** 2022-04-17 01:26 UTC
