### ISSUE TITLE
Unable to change actor appearance

### ISSUE THREAD

**Issue by Rensa** [imchillin/Anamnesis#592] opened 2021-10-29 18:53 UTC
**Describe the bug**
When I attempt to edit the appearance of anyone other than a player in the character tab (or, an NPC/minion etc turned into a player) I am unable to do so.

**To Reproduce**
This happens any time I click on an NPC in the application, for instance, a minion, and turn them in to a player for appearance editing. That's when the 'failed to tick actor' pops up, and I am unable to edit their appearance, or save, or load appearances onto them. All of the options on the page are grayed out. I am on the most recent version of Anamnesis, as I reinstalled the tool before making this report to make sure, along with a PC restart, and multiple XIV restarts as well. To note, this also doesn't seem to work on NPCs that were editable in the past. Only player characters are editable, even if one converts an NPC in to a player, it does not work.
[2021-10-29-14-42-36.txt](https://github.com/imchillin/Anamnesis/files/7444332/2021-10-29-14-42-36.txt)

**Comment by Ani-ki** [comment] 2021-10-29 21:29
While this isn't the exact same issue as #578, it's caused by the same problem, which has been resolved as part of the memory system overhaul that's been worked on over the last couple of weeks, and is fixed in the build we hope to have out later today. I'll keep this one open just in case, though.

**Comment by Rensa** [comment] 2021-10-29 21:34
Great! I'll try the update when its released and update this thread accordingly to see if the issue is resolved.

**Comment by Rensa** [comment] 2021-10-31 20:11
Unfortunately, the update seems to have made the issue even worse, as now I am unable to turn actors in to players at all. Not any NPC or any minion.

**Comment by Ani-ki** [comment] 2021-11-04 22:16
Not sure why this was closed by OP? If the issue isn't resolved, it should stay open.

Are you manually trying to change actors into Player entities?

**Comment by Ani-ki** [comment] 2021-11-04 22:17
@Rensa when you have a moment, we'd appreciate an update from you here.

**Comment by kestes05** [comment] 2021-11-11 20:40
I am having a similar issue. Sometimes, clicking on items will not respond to the character in game, such as changing a clothing item. The change will show in the tool, but not reflect in the game. Occasionally, the "failed to tick selected actor" will pop up in the tool window after about 20-30 seconds if no additional change is made to the clothing item that it did not render.

It doesn't happen on every change: it seems to be about 1 out of every 4-5 clicks on clothing changes that it does not render and pop the error.

**Comment by Yuuki-Walsh** [comment] 2021-11-14 06:59
that particular issue is being tracked over at #614

**Comment by Ani-ki** [comment] 2021-11-18 06:16
No response from OP. :/

**Closed by Ani-ki** 2021-11-18 06:16 UTC
Labels: Bug, Actor
