### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by Caunedhiel** [imchillin/Anamnesis#968] opened 2022-04-16 21:39 UTC
**Describe the bug**
Did not start normally. Reinstalled and restarted PC. Disabled anitvirus. Game up to date.

![Screenshot 2022-04-16 173328](https://user-images.githubusercontent.com/103859799/163692155-92fbc496-2b19-479c-a2cd-aeb259a4bd5d.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Entered game with chosen character
2. Click to open Anamnesis
3. See error

**Log file**
[2022-04-16-17-32-31.txt](https://github.com/imchillin/Anamnesis/files/8500685/2022-04-16-17-32-31.txt)

**Comment by Ty0sMatic** [comment] 2022-04-16 22:55
That is the case because Ana hasn't been updated to the latest version yet. Devs are working on it. Be patient :)

**Comment by Ani-ki** [comment] 2022-04-16 23:19
Duplicate of #937

**Closed** 2022-04-16 23:19 UTC
Labels: Duplicate
