### ISSUE TITLE
Critical Error upon opening - 'GameDataService Error: Failed to initialize Lumina (Are your game files up to date?)' 

### ISSUE THREAD

**Issue by Ocean1148** [imchillin/Anamnesis#978] opened 2022-04-17 23:07 UTC
2022-04-17 19:01:38.320 -04:00 [INF] OS: Microsoft Windows 10.0.19044
2022-04-17 19:01:38.321 -04:00 [INF] Framework: .NET 5.0.8
2022-04-17 19:01:38.322 -04:00 [INF] OS Architecture: X64
2022-04-17 19:01:38.322 -04:00 [INF] Process Architecture: X64
2022-04-17 19:01:38.322 -04:00 [INF] Anamnesis Version: 2022-03-24 12:09
2022-04-17 19:01:38.322 -04:00 [INF] Check Working Directory: "C:\Users\Luke\Downloads\New folder"
2022-04-17 19:01:38.333 -04:00 [INF] Initialized service: LogService
2022-04-17 19:01:38.344 -04:00 [INF] Initialized service: SerializerService
2022-04-17 19:01:38.400 -04:00 [INF] Initialized service: SettingsService
2022-04-17 19:01:38.930 -04:00 [INF] Initialized service: UpdateService
2022-04-17 19:01:38.938 -04:00 [INF] Initialized service: LocalizationService
2022-04-17 19:01:38.938 -04:00 [INF] Initialized service: ViewService
2022-04-17 19:01:38.949 -04:00 [INF] Opening game process: D:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\ffxiv_dx11.exe
2022-04-17 19:01:38.956 -04:00 [INF] Found game version: 2022.04.07.0000.0000
2022-04-17 19:01:38.956 -04:00 [WRN] Unrecognized game version: 2022.04.07.0000.0000. Current validated version is: 2022.03.01.0000.0000
2022-04-17 19:01:39.066 -04:00 [INF] Signature Scanner Created: ffxiv_dx11.exe
2022-04-17 19:01:39.066 -04:00 [INF] Module Text base: 140703012753408
2022-04-17 19:01:39.067 -04:00 [INF] Module Text size: 24749698
2022-04-17 19:01:39.067 -04:00 [INF] Module Data base: 140703043493888
2022-04-17 19:01:39.067 -04:00 [INF] Module Data size: 6799416
2022-04-17 19:01:39.657 -04:00 [INF] Took 589ms to scan for 23 addresses
2022-04-17 19:01:39.815 -04:00 [INF] Initialized service: MemoryService
2022-04-17 19:01:39.815 -04:00 [INF] Initialized service: AddressService
2022-04-17 19:01:39.821 -04:00 [INF] Initialized service: ActorService
2022-04-17 19:01:39.830 -04:00 [INF] Initialized service: TargetService
2022-04-17 19:01:39.832 -04:00 [INF] Initialized service: FileService
2022-04-17 19:01:39.832 -04:00 [INF] Initialized service: TerritoryService
2022-04-17 19:01:39.832 -04:00 [INF] Initialized service: GameService
2022-04-17 19:01:39.833 -04:00 [INF] Initialized service: TimeService
2022-04-17 19:01:39.836 -04:00 [INF] Initialized service: CameraService
2022-04-17 19:01:39.837 -04:00 [INF] Initialized service: GposeService
2022-04-17 19:01:39.894 -04:00 [INF] Found game client region: Global
2022-04-17 19:01:40.599 -04:00 [DBG] sheet Race not in cache - creating new sheet for language "English"
2022-04-17 19:01:40.612 -04:00 [DBG] sheet Tribe not in cache - creating new sheet for language "English"
2022-04-17 19:01:40.613 -04:00 [DBG] sheet Item not in cache - creating new sheet for language "English"
2022-04-17 19:01:40.683 -04:00 [DBG] sheet Stain not in cache - creating new sheet for language "English"
2022-04-17 19:01:40.684 -04:00 [DBG] sheet ENpcBase not in cache - creating new sheet for language "English"
2022-04-17 19:01:40.735 -04:00 [DBG] sheet BNpcBase not in cache - creating new sheet for language "English"
2022-04-17 19:01:40.736 -04:00 [WRN] The sheet Anamnesis.GameData.Excel.BattleNpc hash doesn't match the hash generated from the header. Expected: 3717274695 actual: 4253945531
2022-04-17 19:01:40.736 -04:00 [FTL] GameDataService Error: Failed to initialize Lumina (Are your game files up to date?)
System.Exception: Failed to initialize Lumina (Are your game files up to date?)
 ---> Lumina.Excel.Exceptions.ExcelSheetColumnChecksumMismatchException: sheet BNpcBase column hash mismatch! expected hash: dd911c47, actual hash: fd8e0ebb!
   at Anamnesis.GameData.Sheets.ExcelSheet`1.GetSheet(GameData lumina, String name, Language language, Nullable`1 expectedHash)
   at Anamnesis.GameData.Sheets.ExcelSheet`1.GetSheet(GameData lumina)
   at Anamnesis.Services.GameDataService.GetSheet[T]()
   at Anamnesis.Services.GameDataService.Initialize()
   --- End of inner exception stack trace ---
   at Anamnesis.Services.GameDataService.Initialize()
   at Anamnesis.Services.ServiceManager.Add[T]()

**Comment by Ocean1148** [comment] 2022-04-17 23:25
Keep up the amazing work <3

**Comment by Peebs-miqo** [comment] 2022-04-17 23:27
Duplicate of #937

**Closed by Peebs-miqo** 2022-04-17 23:27 UTC
